In [5]:
import pandas as pd
import numpy as np
from IPython.display import display

folder='C:/myPyExcel/data/ch05/'
readFile=folder+"학생평가.csv"

data=pd.read_csv(readFile, encoding='cp949')
display(data)

# data를 '학과'필드로 그룹화 해서 '중간고사' 필드들의 합계를 구한다. - 1개의 그룹
df=data.groupby('학과')

display(data[(data['학과']=='경영학과') & (data['중간고사']>=90)]['과제점수'].sum())


# for key, group in df:
#     print('* key : ',key)
#     print('* member : ',len(group))
#     display(group.head())

          학번   성명  학년   학과코드      학과  평가1  중간고사  평가2  기말고사  출석점수  과제점수
0   20180207  최경민   4  SOC02    경제학과   67    90   70    80    90    80
1   20200620  조현호   2  ENG02    전산학과   90    95   80    90    90    70
2   20200623  김선국   2  ENG02    전산학과   78    85   70    90    90    80
3   20180707  이컴도   4  ENG01  컴퓨터공학과   90    95   85   100    95    85
4   20210317  박수민   1  HUM01  국어국문학과   70    90   80    95    90    80
5   20200407  이서민   2  SOC03  사회복지학과   53    90   80    95   100    95
6   20210413  김율도   1  SOC03  사회복지학과   74    86   90    85    95    90
7   20180512  최강민   4  HUM02  영어영문학과   78    85   70    85    95    90
8   20160611  한성균   4  ENG02    전산학과   90   100   95    80    85    80
9   20160315  강병목   4  HUM01  국어국문학과   73    85   70    90   100    80
10  20210154  심영란   1  SOC01    경영학과   78    85   75    90   100    90
11  20170701  김영원   3  ENG01  컴퓨터공학과   95   100   90    95   100    95
12  20190128  김보미   3  SOC01    경영학과   88    90   85    95   100    90
13  20210123  김민률   1  SOC01    경영학과   68    87   65    88   100    80
14  20160311  김민찬   4  HUM01  국어국문학과   63    90   65    80    95    70
15  20190729  문희선   3  ENG01  컴퓨터공학과   90    95   95   100    95    90
16  20190213  나경제   3  SOC02    경제학과   75    95   70    80    95    90
17  20190214  임영민   3  SOC02    경제학과   88    95   83    90    95    75
18  20170101  나영웅   3  SOC01    경영학과   85    95   90    90    95    95
19  20210302  김영지   1  HUM01  국어국문학과   53    50   60    55    70    80
20  20210732  최민경   1  ENG01  컴퓨터공학과   75    80   70    85    90    80
21  20200527  이철호   2  HUM02  영어영문학과   70    85   75    90    95    78
22  20170617  강호동   3  ENG02    전산학과   85    95   90    90    95    80
23  20180714  복솔이   4  ENG01  컴퓨터공학과   95   100   90    95    90    90
24  20180401  유재석   4  SOC03  사회복지학과   93    90   85    95   100    90
25  20180522  최슬기   4  HUM02  영어영문학과   96    90   95   100    75    90

185