## Pandas로 Excel 파일 불러 오기
### pd.read_excel(excel_file)  :  excel_file 은 전체 경로+파일명 
#### 엑셀 데이터의 첫번째 행이 columns 데이터가 되고,  index 값은 0 부터 자동으로 설정된다.

#### 옵션 : index_col = '열이름' 혹은 열 번호 / sheet_name = '시트명' 혹은 시트번호(기본 : 0) / header = 행 번호 혹은None / names=column데이터  /  skiprows : 엑셀을 읽을 때 첫줄(0)으로 부터 몇 줄을 건너뛸지 지정  /  nrows : 몇 줄을 읽을지 지정 / usecols='B:D' : B~D 열만 읽어 온다. 
#### index_col 과 names 는 동시에 사용 할 수 없다

In [1]:
import pandas as pd
folder='c:/myPyExcel/data/ch05/'
excel_file=folder+'사원별_월간_판매현황.xlsx'

df=pd.read_excel(excel_file)

# '이름' 열을 index로
df1=pd.read_excel(excel_file, index_col="이름")

# 기존의 열 이름 대신에  사용자가 열 이름을 지정 : 기존의 column으르 제외하고 불러 와 진다.
# header=0 으로 지정 하면 동일한 결과를 가져 온다. 
df2=pd.read_excel(excel_file, names=['a','b','c','d','e','f','g'])

# '사원별_월간_판매현황2.xlsx' 에는 'sheet1'과 '하반기' 시트가 있다. 
exel_file2=folder+'사원별_월간_판매현황2.xlsx'

# '사원별_월간_판매현황2.xlsx' 에서 '하반기' 시트의 데이터 불러 오기
df3= pd.read_excel(exel_file2, sheet_name='하반기')

df2

     a   b   c   d   e   f   g
0  양동호  69  54  76  34  67  56
1  조순열  65  47  85  12  56  34
2  박영순  76  85  57  42  89  91
3  고지영  98  69  23  82  67  87
4  지수경  45  39  56  98  34  53
5  오선호  56  34  56  76  95  73
6  진가연  90  57  34  44  58  96
7  최소진  45  63  76  15  85  54
8  한영미  81  75  23  97  53  95

### 불러 오는 데이터의 영역 지정

In [2]:
import pandas as pd
folder='c:/myPyExcel/data/ch05/'
file=folder+'readData.xlsx'

# sheet_name=0 :첫번째 시트에서
# skiprows=2 : 2줄 건너뛰고(3행부터), 
# nrows=4 : 5개의 행을 불러 오며, 첫번째 행은 columnData가 된다.
# usecols='B:H', 
# B~H 열만 대상으로 한다.(B3:H7 영역)
df1=pd.read_excel(file, sheet_name=0, skiprows=2, nrows=4, usecols='B:H')
df1

      도서명   저자  매입수량  주문수량  배송수량  재고수량       배송율
0  믿어준 사람  김미후   178   156   140    22  0.897436
1    건강보감  나오미   145   132   130    13  0.984848
2    낙타바늘  사오정   167   150   150    17  1.000000
3    하늘아래  손오공   250   234   120    16  0.512821

## Pandas로 Excel 에 데이터 기록 
### df.to_excel(excel_file)  :  DataFrame 'df'를 'excel_file'에 기록 
#### 옵션 : index = True/False  ,  header = True/False  ,  sheet_name = '시트명'  ,  startrow = 시작행(0행부터)  ,  startcol = 시작열(0 부터)

In [3]:
import pandas as pd
folder='c:/myPyExcel/data/ch05/'
excel_file=folder+'사원별_월간_판매현황2.xlsx'
excel_file1=folder+'사원별_월간_판매현황_two_sheets.xlsx'

df1=pd.read_excel(excel_file, sheet_name=0)
df2=pd.read_excel(excel_file, sheet_name=1)

df1.to_excel(excel_file1)
#df2.to_excel(excel_file1, startrow = 0 , startcol=10)

### 여러개의 DataFrame 데이터를 엑셀 파일에 기록
#### xlsxwriter  혹은  Openpyxl  같은 라이브러리르 사용 해야 한다.(아나콘다에는 기본적으로 탑재 되어 있다. )
    - xlsxwriter : 속도 빠르지만, 기존 데이터에 이어 쓰기가 안되고, 덮어 쓰기, 혹은 새로만들기만 된다. 
    - openpyxl : 속도 느리지만, 기존 데이터에 이어 쓰기가 가능하다. 
#### writer=pd.ExcelWriter(excel_file, engin='xlsxwriter)
    # Pandas의 ExcelWriter로 engine은 'xlsxwriter' 를 이용해서 엑셀에 기록하기 위한 개체 'writer'를 생성

#### df1.to_excel(writer, sheet_name='시트명')
#### df2.to_excel(writer, sheet_name='시트명')
    # df1과 df2를 'writer'객체를 이용해서, 각각 다른 시트에 기록

In [4]:
import pandas as pd
folder='c:/myPyExcel/data/ch05/'
excel_file=folder+'사원별_월간_판매현황2.xlsx'
wfile=folder+'test.xlsx'

# 사원별_월간_판매현황2.xlsx 문서에서 '상반기' 시트와 '하반기'시트의 데이터를 각각 df1 과 df2로 불러 온다
df1=pd.read_excel(excel_file, sheet_name='상반기')
df2=pd.read_excel(excel_file, sheet_name='하반기')

# 엑셀 문서에 기록 하기 위한 개체 writer 생성
writer=pd.ExcelWriter(wfile, engine='xlsxwriter')

# df1과 df2를 writer 객체를 통해서 엑셀 파일로 기록 한다. 
df1.to_excel(writer, sheet_name='df1')
df2.to_excel(writer, sheet_name='df2')

# writer 객체를 저장 하고 종료
writer.save()

#### with 블럭문 사용 하기 : 마지막에 .save() 를 사용 안 해도 된다.

In [5]:
import pandas as pd
folder='c:/myPyExcel/data/ch05/'
excel_file=folder+'사원별_월간_판매현황2.xlsx'
wfile=folder+'test1.xlsx'

df1=pd.read_excel(excel_file, sheet_name='상반기')
df2=pd.read_excel(excel_file, sheet_name='하반기')

# with 구문 사용
with pd.ExcelWriter(wfile, engine='xlsxwriter') as writer:
    df1.to_excel(writer, sheet_name='df1')
    df2.to_excel(writer, sheet_name='df2')

#### 위의 예제 처럼 'xlsxwriter' 를 사용 하게 문서 혹은 시트를 새로 작성하는것과 동일한 결과를 가져온다. 
#### 기존 문서에 추가로 데이터를 기록 하려면, 'xlsxwriter'가 아닌 'openpyxl' 을 사용하여, mode='a' 옵션을 사용 해야 한다.

In [6]:
import pandas as pd

# 'test.xlsx'에 데이터를 추가 하기 위해 wfile의 경로를 설정
folder='c:/myPyExcel/data/ch05/'
wfile=folder+'test.xlsx'

# 추가하려는 딕셔너리 데이터
dic={
    'A-101':['홍길동',75,83],
    'A-102':['강호동',92,76],
    'B-101':['홍차영',83,82],
    'B-102':['최명순',89,75]
}

df=pd.DataFrame(dic)

# writer 개체를 'openpyxl'과 append 모드로 생성
with pd.ExcelWriter(wfile, engine='openpyxl', mode='a') as writer:
    df.to_excel(writer, sheet_name='추가데이터', index=False)

#### 엑셀 데이터 중에서 조건에 맞는 데이터만 추출 해서 다시 기록 하기
#### 매입 수량이 200~300 인 데이터만을 추출 및 가공 해서 test2에 새로운 시트를 만들어서 기록 해 보자

In [7]:
import pandas as pd
import openpyxl as op

folder='c:/myPyExcel/data/ch05/'
readFile = folder+'readData.xlsx'
writeFile = folder+'test2.xlsx'

# 조건에 맞는 데이터를 딕셔너리 데이터로 만들기 위한 리스트 생성
bookName=[]
author=[]
puNum=[]
orNum=[]
delNum=[]
praNum=[]

# 엑셀에서 데이터 읽어오기
df1=pd.read_excel(readFile, sheet_name=0, skiprows=2, usecols='B:H')
df2=pd.read_excel(readFile, sheet_name=1, skiprows=2, usecols='b:h')
df3=pd.read_excel(readFile, sheet_name=2, skiprows=1, usecols='a:f,h')


i=0

# 0 ~ df1의 길이 만큼 반복문을 통해서 매입수량이 200 ~ 400 인 데이터를 검색해서 리스트에 추가
for i in range(i,len(df1)):    
    if df1.iloc[i]['매입수량'] > 200 and df1.iloc[i]['매입수량'] < 400 :
        bookName.append(df1.iloc[i]['도서명'])
        author.append(df1.iloc[i]['저자'])
        puNum.append(df1.iloc[i]['매입수량']*1.1)
        orNum.append(df1.iloc[i]['주문수량']*1.1)
        delNum.append(df1.iloc[i]['배송수량']*1.1)
        praNum.append(df1.iloc[i]['재고수량'])

dic={
    '도서명':bookName,
    '저자':author,
    '매입수량':puNum,
    '주문수량':orNum,
    '배송수량':delNum,
    '재고수량':praNum
}

df1=pd.DataFrame(dic)

with pd.ExcelWriter(writeFile, engine='openpyxl', mode='a') as writer:
    df1.to_excel(writer, sheet_name='결과값', index=False)

#### 여러 개의 DataFrame 을 하나의 worksheet에 추가 하는 방법

In [ ]:
import pandas as pd
folder='c:/myPyExcel/data/ch05/'
readFile = folder+'readData.xlsx'
writeFile = folder+'test2.xlsx'

df1=pd.read_excel(readFile, sheet_name=0, skiprows=2, usecols='B:H')
df2=pd.read_excel(readFile, sheet_name=1, skiprows=2, usecols='b:h')
df3=pd.read_excel(readFile, sheet_name=2, skiprows=1, usecols='a:f,h')

with pd.ExcelWriter(writeFile, engine='xlsxwriter') as writer:
    df1.to_excel(writer, sheet_name='df1', index=False)
    df2.to_excel(writer, sheet_name='df1', index=False, startrow=11)
    df3.to_excel(writer, sheet_name='df1', index=False, startrow=0, startcol=8)

#### CSV 파일 읽어서 Excel 파일로 쓰기

In [51]:
import pandas as pd
import numpy as np

folder='c:/myPyExcel/data/ch05/'
csvFile = folder+'csvData.txt'
tmpList=[]

df=pd.read_csv(csvFile, header=None)

i=0

for i in range(len(df)):
   tmpList.append(df.iloc[i][0])
 

arr=np.array(tmpList)
arr1=arr.reshape(-1,4)

df1=pd.DataFrame(arr1)

       0    1       2     3
0  a-101  이민재    경영학과  2500
1  b-101  홍길동  컴퓨터공학과  3200
2   a-10  강감찬    경영학과  1500
3  b-102  유기석  컴퓨터공학과  2700
4  b-103  신동엽  컴퓨터공학과  4300